version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.4.0
    working_directory: ~/timefly
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "yarn.lock" }}
      - run:
          name: install
          command: yarn
      - save_cache:
          key: cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: build
          command: yarn build
      - persist_to_workspace:
          root: ./
          paths:
            - build
  deploy:
    machine:
      enabled: true
    working_directory: ~/timefly
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - 49:07:e3:ef:41:45:f2:c6:96:47:88:9f:c0:56:03:5d
      - run:
          name: Deploy over SSH
          command: |
            scp -i ~/.ssh/id_rsa_4907e3ef4145f2c69647889fc056035d -r ~/timefly deploy@dwik.se:/var/www/applications/timefly
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master