version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:11.4.0
    working_directory: ~/timefly
    steps:
      - checkout
      - restore_cache:
          key: cache-{{ checksum "yarn.lock" }}
      - run:
          name: clear yarn cache
          command: yarn cache clean
      - run:
          name: install
          command: yarn install --frozen-lockfile
      - save_cache:
          key: cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run:
          name: build
          command: yarn build
  deploy:
    machine:
      enabled: true
    working_directory: ~/timefly
    steps:
      - run:
          name: Deploy over SSH
          command: |
            scp -r ~/timefly deploy@dwik.se:/var/www/applications/timefly
workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master